//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatAppWithDBExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserConnection
    {
        public int id { get; set; }
        public int Userid { get; set; }
        public System.Guid Connectionid { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
